package gateway

import (
	"strings"
	"testing"
)

func TestBuildIdempotencyKey_ClientSupplied(t *testing.T) {
	t.Parallel()
	k, err := buildIdempotencyKey("client-supplied-key-123", "u1", "p1", "ldcpay")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if k != "client-supplied-key-123" {
		t.Fatalf("expected verbatim client key, got %q", k)
	}
}

func TestBuildIdempotencyKey_TrimWhitespace(t *testing.T) {
	t.Parallel()
	k, err := buildIdempotencyKey("  abc  ", "u", "p", "x")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if k != "abc" {
		t.Fatalf("expected trimmed key, got %q", k)
	}
}

func TestBuildIdempotencyKey_AutoGenerated_UniquePerCall(t *testing.T) {
	t.Parallel()
	seen := map[string]struct{}{}
	for i := 0; i < 1000; i++ {
		k, err := buildIdempotencyKey("", "user-A", "plan-pro", "ldcpay")
		if err != nil {
			t.Fatalf("err: %v", err)
		}
		if _, dup := seen[k]; dup {
			t.Fatalf("collision on iteration %d: %q", i, k)
		}
		seen[k] = struct{}{}
		if !strings.HasPrefix(k, "user-A:plan-pro:ldcpay:") {
			t.Fatalf("missing context prefix: %q", k)
		}
	}
}

func TestBuildIdempotencyKey_RejectTooLong(t *testing.T) {
	t.Parallel()
	long := strings.Repeat("x", 129)
	if _, err := buildIdempotencyKey(long, "u", "p", "x"); err == nil {
		t.Fatal("expected error for >128 chars")
	}
}

func TestBuildIdempotencyKey_RejectNonPrintable(t *testing.T) {
	t.Parallel()
	cases := []string{
		"abc\ndef",
		"abc\tdef",
		"abc def", // 包含空格 0x20，按 [0x21-0x7e] 也算非可打印
		"abc\x00def",
		"中文",
	}
	for _, c := range cases {
		if _, err := buildIdempotencyKey(c, "u", "p", "x"); err == nil {
			t.Errorf("expected error for non-printable %q", c)
		}
	}
}

func TestNewSubscribeIdemKey_UniquePerCall(t *testing.T) {
	t.Parallel()
	seen := map[string]struct{}{}
	for i := 0; i < 1000; i++ {
		k, err := newSubscribeIdemKey("u", "pro", "ldcpay")
		if err != nil {
			t.Fatalf("err: %v", err)
		}
		if _, dup := seen[k]; dup {
			t.Fatalf("collision: %q", k)
		}
		seen[k] = struct{}{}
		if !strings.HasPrefix(k, "u|pro|ldcpay|") {
			t.Fatalf("missing context prefix: %q", k)
		}
	}
}

func TestBuildTopupIdemKey_UniquePerCall(t *testing.T) {
	t.Parallel()
	seen := map[string]struct{}{}
	for i := 0; i < 1000; i++ {
		k, err := buildTopupIdemKey("u-42", 5000)
		if err != nil {
			t.Fatalf("err: %v", err)
		}
		if _, dup := seen[k]; dup {
			t.Fatalf("collision: %q", k)
		}
		seen[k] = struct{}{}
		if !strings.HasPrefix(k, "topup:u-42:5000:") {
			t.Fatalf("missing context prefix: %q", k)
		}
	}
}
